import { Educator } from "@/types/community";

export const educatorsData: Educator[] = [
  {
    name: "ABC",
    role: "Middle School Math · Curriculum Lead",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ABC",
    resources: "56",
    followers: "1.2k",
    coTeaching: "14 projects",
    alignment: 86,
    specialTags: ["Top contributor", "STEM"],
    tags: ["Algebra", "Formative assessment", "Differentiation"],
    following: false,
  },
  {
    name: "DEF",
    role: "High School Science · Lab Coordinator",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=DEF",
    resources: "42",
    followers: "892",
    coTeaching: "7 projects",
    alignment: 74,
    specialTags: ["NGSS pioneer"],
    tags: ["Inquiry labs", "Safety", "Grade 9-10"],
    following: true,
  },
  {
    name: "GHI",
    role: "Elementary Literacy · Instructional Coach",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=GHI",
    resources: "68",
    followers: "2.1k",
    coTeaching: "21 projects",
    alignment: 91,
    specialTags: ["Mentor"],
    tags: ["Reading - K-3", "Phonics", "Family engagement", "Bilingual"],
    following: false,
  },
  {
    name: "JKL",
    role: "Art & Design · Project-Based Learning",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=JKL",
    resources: "31",
    followers: "503",
    coTeaching: "8 projects",
    alignment: 63,
    specialTags: ["Project-based"],
    tags: ["Portfolios", "Critique circles", "Community murals"],
    following: true,
  },
  {
    name: "MNO",
    role: "World Languages · Department Chair",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=MNO",
    resources: "47",
    followers: "1.6k",
    coTeaching: "12 projects",
    alignment: 79,
    specialTags: ["Language lab"],
    tags: ["Speaking tasks", "Stations", "AP prep"],
    following: false,
  },
  {
    name: "PQR",
    role: "Special Education · Inclusion Specialist",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=PQR",
    resources: "39",
    followers: "643",
    coTeaching: "18 projects",
    alignment: 88,
    specialTags: ["Inclusive practices"],
    tags: ["IEP", "Co-teaching models", "Behavior supports"],
    following: false,
  },
];