import { ResourceCardProps } from "@/types/resources";

export const myResourcesData: ResourceCardProps[] = [
  {
    title: "Introduction to Algebra",
    category: "Mathematics",
    type: "Grade 7 · Worksheet",
    downloads: "312",
    likes: "98",
    updated: "1 hr ago",
    curriculum: "Common Core",
    coTeachers: "2",
    visibility: "Public",
    status: "Published",
  },
  {
    title: "Creative Writing Workshop",
    category: "English",
    type: "Mixed Grades · Lesson Plan",
    downloads: "184",
    likes: "64",
    updated: "3 days ago",
    curriculum: "Local",
    coTeachers: "1",
    visibility: "Public",
    status: "Published",
  },
  {
    title: "Science Lab Safety Guide",
    category: "Science",
    type: "Grade 8 · Slide Deck",
    downloads: "421",
    likes: "152",
    updated: "1 week ago",
    curriculum: "NGSS",
    coTeachers: "0",
    visibility: "Public",
    status: "Featured",
  },
  {
    title: "History Timeline Project",
    category: "History",
    type: "Grade 6 · Project",
    downloads: "0",
    likes: "-",
    updated: "2 days ago",
    curriculum: "Inquiry",
    coTeachers: "1",
    visibility: "Private",
    status: "Draft",
  },
  {
    title: "Art Techniques Guide",
    category: "Arts",
    type: "Mixed Grades · Guide",
    downloads: "132",
    likes: "65",
    updated: "1 week ago",
    curriculum: "Open",
    coTeachers: "0",
    visibility: "Public",
    status: "Published",
  },
  {
    title: "Music Theory Basics",
    category: "Music",
    type: "High School · Lesson",
    downloads: "103",
    likes: "51",
    updated: "1 month ago",
    curriculum: "Performance",
    coTeachers: "0",
    visibility: "Public",
    status: "Published",
  },
  {
    title: "Formative Quiz Bank",
    category: "Mathematics",
    type: "Grades 6-8 · Quiz Pack",
    downloads: "76",
    likes: "29",
    updated: "5 days ago",
    curriculum: "Common Core",
    coTeachers: "3",
    visibility: "Shared",
    status: "Published",
  },
  {
    title: "Parent Communication Template",
    category: "General",
    type: "All Grades · Document",
    downloads: "205",
    likes: "87",
    updated: "2 weeks ago",
    curriculum: "—",
    coTeachers: "0",
    visibility: "Public",
    status: "Published",
  },
  {
    title: "Project Rubric Template",
    category: "Cross-curricular",
    type: "Rubric",
    downloads: "—",
    likes: "-",
    updated: "4 hours ago",
    curriculum: "Rubric",
    coTeachers: "0",
    visibility: "Private",
    status: "Draft",
  },
];
